export const UI_TEXT = {
  PLACEHOLDER: 'Enter your task...',
  ADD_BUTTON: 'Add Task',
  EMPTY_STATE: 'No tasks yet. Add your first task above!',
  ERROR_REQUIRED: 'Task cannot be empty',
  ERROR_TOO_LONG: 'Task is too long',
  ERROR_UNEXPECTED: 'An unexpected error occurred. Please try again.',
  ERROR_NETWORK: 'Network error. Please check your connection.',
  SORT_NEWEST: 'Newest First',
  SORT_OLDEST: 'Oldest First',
  SORT_A_Z: 'A-Z',
  SORT_Z_A: 'Z-A',
  SORT_LABEL: 'Sort by',
  FILTER_ALL: 'All',
  FILTER_ACTIVE: 'Active',
  FILTER_COMPLETED: 'Completed',
} as const;
